# LaTeX Makefile
SHELL := /bin/bash
FILE=main
cleanregex = ".+\(aux\|log\|synctex.gz\|fls\|fdb_latexmk\|bbl\|blg\)$$"
cleanpdfregex = ".+/content/.+\(pdf\)$$"
cleanallregex = ".+\(aux\|log\|synctex.gz\|fls\|fdb_latexmk\|bbl\|blg\|pdf\)$$"

.PHONY: clean clean-p $(FILE).pdf

$(FILE).pdf: 
	echo "dictionary, skipping"

all:
	echo "dictionary, skipping"

clean:
	echo "dictionary, skipping"

clean-p:
	echo "dictionary, skipping"

clean-a:
	echo "dictionary, skipping"

contents:
	echo "dictionary, skipping"

ac: contents clean-a $(FILE).pdf clean